spring:
  datasource:
    url: jdbc:postgresql://localhost:55432/imageLiteApp
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  servelet:
    multipar:
      max-file-size: 20MB
      max-request-size: 20MB